WITH inventory AS (
SELECT 
    PRODUCT_CODE, SNAPSHOT_DATE, WAREHOUSE_CODE, 
    SUM(QUANTITY_ON_HAND) AS total_inventory_qty
    -- MAX(SNAPSHOT_DATE)OVER(PARTITION BY PRODUCT_CODE, WAREHOUSE_CODE) AS latest_inventory_date
FROM {{ source('demo', 'inventory_transaction') }}
GROUP BY 1,2,3
QUALIFY SNAPSHOT_DATE = MAX(SNAPSHOT_DATE)OVER(PARTITION BY PRODUCT_CODE, WAREHOUSE_CODE)
)

SELECT * FROM inventory