sources:
  - name: demo
    database: demo
    schema: dev
    tables:
      - name: inventory_transaction
      - name: product_category_null
      - name: product_master
      - name: receipt_transaction
      - name: shipment_transaction